# CMake generated Testfile for 
# Source directory: /workspace/PrismLauncher/tests
# Build directory: /workspace/PrismLauncher/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(FileSystem "/workspace/PrismLauncher/FileSystem")
set_tests_properties(FileSystem PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;3;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(GZip "/workspace/PrismLauncher/GZip")
set_tests_properties(GZip PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;6;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(GradleSpecifier "/workspace/PrismLauncher/GradleSpecifier")
set_tests_properties(GradleSpecifier PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;9;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(PackageManifest "/workspace/PrismLauncher/PackageManifest")
set_tests_properties(PackageManifest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;12;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(MojangVersionFormat "/workspace/PrismLauncher/MojangVersionFormat")
set_tests_properties(MojangVersionFormat PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;15;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(Library "/workspace/PrismLauncher/Library")
set_tests_properties(Library PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;18;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(ResourceFolderModel "/workspace/PrismLauncher/ResourceFolderModel")
set_tests_properties(ResourceFolderModel PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;21;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(ResourcePackParse "/workspace/PrismLauncher/ResourcePackParse")
set_tests_properties(ResourcePackParse PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;24;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(ResourceModel "/workspace/PrismLauncher/ResourceModel")
set_tests_properties(ResourceModel PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;27;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(TexturePackParse "/workspace/PrismLauncher/TexturePackParse")
set_tests_properties(TexturePackParse PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;30;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(DataPackParse "/workspace/PrismLauncher/DataPackParse")
set_tests_properties(DataPackParse PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;33;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(ShaderPackParse "/workspace/PrismLauncher/ShaderPackParse")
set_tests_properties(ShaderPackParse PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;36;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(WorldSaveParse "/workspace/PrismLauncher/WorldSaveParse")
set_tests_properties(WorldSaveParse PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;39;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(ParseUtils "/workspace/PrismLauncher/ParseUtils")
set_tests_properties(ParseUtils PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;42;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(Task "/workspace/PrismLauncher/Task")
set_tests_properties(Task PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;45;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(INIFile "/workspace/PrismLauncher/INIFile")
set_tests_properties(INIFile PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;48;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(JavaVersion "/workspace/PrismLauncher/JavaVersion")
set_tests_properties(JavaVersion PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;51;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(Packwiz "/workspace/PrismLauncher/Packwiz")
set_tests_properties(Packwiz PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;54;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(Index "/workspace/PrismLauncher/Index")
set_tests_properties(Index PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;57;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
add_test(Version "/workspace/PrismLauncher/Version")
set_tests_properties(Version PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/workspace/PrismLauncher:" _BACKTRACE_TRIPLES "/nix/store/skg75479gbb8dzzxmqfmx5pbjhd5gyp4-extra-cmake-modules-5.104.0/share/ECM/modules/ECMAddTests.cmake;96;add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;60;ecm_add_test;/workspace/PrismLauncher/tests/CMakeLists.txt;0;")
